apiVersion: v1
kind: Namespace
metadata: 
  name: hdfc

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: hdfc
  name: nginx-deploy
  labels: 
    app: nginx
spec: 
  replicas: 2
  selector: 
   matchLabels: 
     app: nginx
  strategy: 
    type: RollingUpdate
  template: 
   metadata: 
     labels: 
       app: nginx
   spec: 
    containers: 
      - name: webserver
        image: nginx:1.21
        ports: 
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata: 
 namespace: hdfc
 name: nginx-service
spec: 
 selector: 
   app: nginx
 type: NodePort
 port: 
   - targetPort: 80
     nodePort: 3000                    7

